name: reviewdog
on:                             [pull_request]
jobs:
  actionlint:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
              - uses: actions/checkout@v4
              - uses: reviewdog/action-actionlint@v1
                with:
                  reporter: github-pr-review
