name: reviewdog
on: 
  push: 
   branches: []
jobs:
  actionlint:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
              - uses: actions/checkout@v4
              - uses: reviewdog/action-actionlint@v1
                with:
                  level: info 
                  github_token: ${{ github.token }}
