name: Compliance check and build test


env:

     APP_PATH: "/sps-backend" # example "/backend" for monorepos or "" for multi repos

on: # defining on which triggers this action should run
  push:
    branches:
      # define on push of which branches should this action be run
    paths:
     - "sps-backend/**"     # define the concrete paths on which a change triggers this action, e.g. backend/**
     - ".github/workflows/**"     # define the concrete paths on which a change triggers this action, e.g. backend/**
  pull_request: # trigger this action also on Pull Requests
    types: [ opened, reopened ]
     
jobs:

  build-maven:

        uses: it-at-m/.github/.github/workflows/reuseable-template-maven-node-build.yml@reuseable-workflow
        with:
           app-path: "./sps-backend"
  
 #build-image:
 #       needs: build-maven
 #       uses: it-at-m/.github/.github/workflows/reuseable-template-build-image.yml@reuseable-workflow
 #       with: 

#          app-path: "/sps-backend" # ${{ env.APP_PATH }}
#        secrets:
#           registry-password: ${{ secrets.GITHUB_TOKEN }}

  build-image:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - id: abc
      uses:  it-at-m/.github/.github/actions/action-build-image/action.yml@reuseable-workflow
      with: 
        app-path: "${{ env.APP_PATH }}"
        registry-password: ${{ secrets.GITHUB_TOKEN }}
