name: Trivy security scan
on:
  push: 
  pull_request:
  schedule:
    - cron: '0 3 * * *' # Daily at 03:00 UTC
jobs:
  scan:
    name: Security check
    runs-on: ubuntu-latest
    permissions:
      contents: read          # Required to checkout and read repo files
      security-events: write  # Required to upload SARIF files to Security tab
    if: github.event_name != 'schedule' || github.ref == 'refs/heads/main'
    steps:
      - name: Run Trivy security check on repository
        uses: it-at-m/lhm_actions/action-templates/actions/action-trivy@212-sarif-export-and-codeql-upload-for-trivy-action

